name: Node.js Continuous Delivery

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x, 21.x, 20.x]

    steps:
      - uses: actions/checkout@v2
        name: "Checkout repository"

      - uses: actions/setup-node@v4
        name: "Use Node.js ${{ matrix.node-version }}"
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Install Dependencies"
        run: npm i

      - name: "Install Vercel CLI"
        run: npm i -g vercel

      - name: "Checking Token"
        run: |
          if [ -z "$VERCEL_TOKEN" ]; then
             echo "Error: Secret VERCEL_TOKEN is not set or is empty."
             exit 1
          fi
      - name: "Deploy in Vercel"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: echo "Token" "$VERCEL_TOKEN"

